// ============================================================
// useRaceSimulation — Tick-based race simulation hook
//
// Manages the setInterval that drives simulateLap() calls.
// Player decisions (pit requests, push levels) are fed in each tick.
// When the race is complete, dispatches RACE_COMPLETE.
// ============================================================

import { useEffect, useRef, useCallback } from 'react';
import { useGame }        from '../context/GameContext.jsx';
import { useRaceContext } from '../context/GameContext.jsx';
import { simulateLap, computeFinalResult, initializeRaceState } from '../engine/raceEngine.js';
import { generateRaceWeather } from '../engine/weatherEngine.js';
import { generateAIStrategy }  from '../engine/aiStrategy.js';
import { SIM_SPEED } from '../data/constants.js';
import { CIRCUITS } from '../data/circuits.js';

export function useRaceSimulation() {
  const { state, dispatch } = useGame();
  const {
    raceState, updateRaceState,
    simSpeed, isPaused, setIsPaused,
    playerPitRequest, clearPitRequest,
    playerPushLevels,
  } = useRaceContext();

  const intervalRef  = useRef(null);
  const raceStateRef = useRef(raceState); // ref to avoid stale closure in interval

  // Keep ref in sync
  useEffect(() => {
    raceStateRef.current = raceState;
  }, [raceState]);

  /** Start the race from the beginning */
  const startRace = useCallback(() => {
    if (!state) return;
    const circ = CIRCUITS[state.currentRaceIndex];
    const weekendData = state.weekendData;

    if (!circ || !weekendData) {
      console.warn('No circuit or weekend data — call prepareRaceWeekend first');
      return;
    }

    // Build strategies: player strategies from raceStrategy, AI generated by weekendData
    const allStrategies = { ...weekendData.strategies };
    // Override with player's own strategy choices
    state.playerDriverIds.forEach(id => {
      if (state.raceStrategy[id]) allStrategies[id] = state.raceStrategy[id];
    });

    // Convert qualifying grid to the format raceEngine expects
    const grid = weekendData.grid.map(entry => ({
      driverId:      entry.driverId,
      teamId:        entry.teamId,
      startPosition: entry.gridPosition,
    }));

    const initialState = initializeRaceState(
      circ, grid, allStrategies, weekendData.weather, state.playerTeamId
    );

    updateRaceState(initialState);
    dispatch({ type: 'SEASON_ADVANCE_PHASE', nextPhase: 'RACE' });
    setIsPaused(false);
  }, [state, dispatch, updateRaceState, setIsPaused]);

  /** Advance one lap */
  const tickOneLap = useCallback(() => {
    const current = raceStateRef.current;
    if (!current || current.isComplete) return;

    // Build player decisions from context state
    const pitRequests = new Set();
    const pitCompounds = {};
    Object.entries(playerPitRequest).forEach(([driverId, compound]) => {
      pitRequests.add(driverId);
      pitCompounds[driverId] = compound;
    });

    const pushLevels = new Map(Object.entries(playerPushLevels));

    const playerDecisions = { pitRequests, pushLevels };

    const newLapState = simulateLap(current, playerDecisions);

    // Clear any served pit requests
    pitRequests.forEach(driverId => clearPitRequest(driverId));

    updateRaceState(newLapState);
    dispatch({ type: 'RACE_TICK', newLapState });

    // Race finished?
    if (newLapState.isComplete) {
      setIsPaused(true);
      const result = computeFinalResult(newLapState);
      dispatch({ type: 'RACE_COMPLETE', result });
    }
  }, [playerPitRequest, playerPushLevels, dispatch, updateRaceState, clearPitRequest, setIsPaused]);

  // Run simulation interval
  useEffect(() => {
    if (isPaused || simSpeed === SIM_SPEED.INSTANT) {
      clearInterval(intervalRef.current);
      return;
    }

    intervalRef.current = setInterval(tickOneLap, simSpeed);
    return () => clearInterval(intervalRef.current);
  }, [isPaused, simSpeed, tickOneLap]);

  /** Instant simulation: run all remaining laps synchronously */
  const simulateInstant = useCallback(() => {
    let current = raceStateRef.current;
    if (!current) return;

    while (!current.isComplete) {
      const playerDecisions = { pitRequests: new Set(), pushLevels: new Map() };
      current = simulateLap(current, playerDecisions);
    }

    updateRaceState(current);
    dispatch({ type: 'RACE_TICK', newLapState: current });
    const result = computeFinalResult(current);
    dispatch({ type: 'RACE_COMPLETE', result });
  }, [dispatch, updateRaceState]);

  return {
    startRace,
    tickOneLap,
    simulateInstant,
    isRunning: !isPaused && !!raceState && !raceState?.isComplete,
  };
}
